pipeline { 
    agent any  
    environment {
        def mvn = "/home/pi/apache-maven/bin/mvn"
    }
    stages { 
        stage(' Compile') { 
            steps { 
            	dir("ftvRESTful"){
					sh '${mvn} clean install'
 				}
            }
        }
    }
}